@startuml AddEvent

skinparam sequenceArrowThickness 2
skinparam roundcorner 10

title Add Event / Recurring Event

participant ":AddCommand" as AC
participant ":CategoryList" as CL
participant ":Category" as CAT
participant ":EventList" as EL
participant ":EventUI" as UI
participant ":Calendar" as CAL

 -> AC : add event
activate AC


alt Normal Event
    note right of AC
        validation and parsing has been omitted from this sequence diagram
    end note
    alt invalid input / format
    else else
        AC -> CL : addEvent(categoryIndex, desc, from, to)
        activate CL
        CL --> AC

        AC -> CL : getLatestEvent()
        CL --> AC : Event
        deactivate CL

        AC -> CAL : registerTask(Event)
        activate CAL
        CAL --> AC
        deactivate CAL

        AC -> UI : printEventAdded(event,desc,totalEvents)
        activate UI
        UI --> AC : show added event
        deactivate UI
    end

else Recurring Event
'    AC -> AC : validate input + parse recurring details

    alt invalid input / format
    else else
        AC -> CL : addRecurringWeeklyEvent(eventCategoryIndex, desc, from, to,calendar, endDate, months)
        activate CL

        CL -> CL : increment recurringGroupId
        CL -> CL : create base Event (with groupId)

        note right of CL
        recurringGroupId is incremented once
        and reused for all occurrences
        end note

        CL -> CAT : addRecurringWeeklyEvent(event, calendar, date, months)
        activate CAT

        CAT -> EL : addRecurringWeeklyEvent(event, calendar, date, months)
        activate EL

        EL -> EL : determine boundaryDateTime

        loop every 7 days until boundaryDateTime
            EL -> EL : create Event (same groupId)
            EL -> EL : add to tasks list
            EL -> CAL : registerTask(Event)
            activate CAL
            CAL --> EL
            deactivate CAL
        end

        EL --> CAT
        deactivate EL
        CAT --> CL
        deactivate CAT
        CL --> AC
        deactivate CL

        AC -> UI : printRecurringEventAdded(event)
        activate UI
        UI --> AC : show added recurring event
        deactivate UI
        deactivate AC
    end

@enduml